### ISSUE TITLE
test gicp not good match

### ISSUE THREAD

**Issue by jamefrank** [GDUT-Kyle/gicp_slam#1]
为什么跑出来的结果中，pcl的gicp可以匹配的很好，但是自定义的gicp没有好的匹配结果
这是复现的存在问题吗？
![2024-08-29_15-56](https://github.com/user-attachments/assets/caf41418-1c9b-4065-8987-157183c612d2)

**Comment by GDUT-Kyle** [comment]
你好，这个数据我之前测试过配准没啥问题，应该是后来修改了一些内部参数所以对这个初始值效果不好了
